# Introduction to Numpy

In [1]:
import numpy as np

In [2]:
#  Use np.+<tab> to view available options
# np? # Use for getting documentation of numpy

In [3]:
# L = dict(name='Alice', course='Maths')

L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
import array

L = list(range(10))
i = 'i'
arr = array.array(i, L)
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# li_type = []
# for item in L:
#     li_type.append(type(item))

L = [1, 'One', 2.0, True]
li_type = [type(items) for items in L]

li_type

[int, str, float, bool]

# Creating Arrays Using Numpy

In [7]:
# 1. Create an array from an existing python list
np.array([1, 3, 4, 5, 7, 9.1])

array([1. , 3. , 4. , 5. , 7. , 9.1])

In [8]:
# 2. The datatype of an array can be specified using dtype
print("Float Type array", np.array([1, 3, 4, 5, 7, 9.1], dtype='float'))
print("Int Type array", np.array([1, 3, 4, 5, 7, 9.1], dtype='int'))

Float Type array [1.  3.  4.  5.  7.  9.1]
Int Type array [1 3 4 5 7 9]


In [9]:
# lists = []
# for item in [2, 3, 4]:
#     lists.append(list(range(item, item + 3)))
# print(np.array(lists))

# --------------------------------------------------------------------------------

# 3. Nested lists results in a multi-dimensional array

np.array([range(item, item + 4) for item in [2, 3, 4]])

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [10]:
# Some basic examples:
print("1. Zeros Int array:", np.zeros(5, dtype=int))
print("2. 2x5 Ones Float array:", np.ones((2, 5), dtype=int))
print("3. 2x5 760 Full array:", np.full((2, 5), 760, dtype=int))
print("4. Python Range is Numpy Arrange:", np.arange(1, 15, 2))

1. Zeros Int array: [0 0 0 0 0]
2. 2x5 Ones Float array: [[1 1 1 1 1]
 [1 1 1 1 1]]
3. 2x5 760 Full array: [[760 760 760 760 760]
 [760 760 760 760 760]]
4. Python Range is Numpy Arrange: [ 1  3  5  7  9 11 13]


## Numpy Array Attributes

In [11]:
np.random.seed(1)

ds_1 = np.random.randint(5, size=8)
ds_2 = np.random.randint(5, size=(2, 8))
ds_3 = np.random.randint(5, size=(2, 4, 8))

print("First Dataset:", ds_1) 
print("Second Dataset:", ds_2)
print("Third Dataset:", ds_3)

First Dataset: [3 4 0 1 3 0 0 1]
Second Dataset: [[4 4 1 2 4 2 4 3]
 [4 2 4 2 4 1 1 0]]
Third Dataset: [[[1 1 1 1 0 4 1 0]
  [0 3 2 1 0 3 1 1]
  [3 4 0 1 3 4 2 4]
  [0 3 1 2 0 4 1 2]]

 [[2 1 0 1 3 4 3 1]
  [3 0 0 2 2 1 3 4]
  [2 0 0 1 1 3 0 0]
  [4 2 4 3 3 0 3 4]]]


In [12]:
# Numpy array has the attributes: shape, number of dimensions, dtype, size, item size and total size.

print("Dimensions of Third Dataset:", ds_3.ndim, "dimensions")
print("Shape of Third Dataset:", ds_3.shape)
print("Size of Third Dataset:", ds_3.size)
print("Data type of Third Dataset:", ds_3.dtype)
print("Item Size of Third Dataset:", ds_3.itemsize, "bytes")
print("Total Size of Third Dataset:", ds_3.nbytes, "bytes")

Dimensions of Third Dataset: 3 dimensions
Shape of Third Dataset: (2, 4, 8)
Size of Third Dataset: 64
Data type of Third Dataset: int32
Item Size of Third Dataset: 4 bytes
Total Size of Third Dataset: 256 bytes


## Array Indexing

In [13]:
# 1. Indexing is similar to python's indexing, put number in square brackets startinging from 0

# Using our first dataset(one-dimensional)
print("First Dataset:", ds_1)
print("First Element:", ds_1[0])
print("Third Element:", ds_1[2])

# You can access the elements from the pther end using negative index
print("The last Element:", ds_1[-1])
print("The Third Element from the Last:", ds_1[2])

First Dataset: [3 4 0 1 3 0 0 1]
First Element: 3
Third Element: 0
The last Element: 1
The Third Element from the Last: 0


In [14]:
# 2. You can access a multidimensional element using a comma seperated tuple of indices

# Using our second dataset(two-dimensional)
print("Second Dataset:", ds_2)
print("First Element:", ds_2[0, 0])
print("Third Element:", ds_2[0, 2])
print("Fourth Element on the Second Row:", ds_2[1, 3])

# You can access the elements from the pther end using negative index
print("The last Element on the Second Row:", ds_2[1, -1])
print("The Third Element from the Last on the First Row:", ds_2[0, 2])


Second Dataset: [[4 4 1 2 4 2 4 3]
 [4 2 4 2 4 1 1 0]]
First Element: 4
Third Element: 1
Fourth Element on the Second Row: 2
The last Element on the Second Row: 0
The Third Element from the Last on the First Row: 1


## Array Slicing

In [15]:
# This follows the syntax: df[start:stop:step]

# For easy assimilation, lets use an ordered list here
df = np.arange(11)
df

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Examples using one-dimensional subarrays

print("----------------------------------------------------------------------------------")
print("First Five(5) Elements df[:5] =", df[:5])
print("All Elements after index 5 df[5:]", df[5:])
print("Some elements in the middle df[3:7]", df[3:7])
print("All even elements df[::2]", df[::2])
print("All stepped element starting from index 1 df[1::2]", df[1::2])

# Reversing the array by using negative steps
print("----------------------------------------------------------------------------------")
print("👈Reversed Array df[::-1]:", df[::-1])
print("👈Stepped Reverse from 7 df[7::-2]:", df[7::-2])

----------------------------------------------------------------------------------
First Five(5) Elements df[:5] = [0 1 2 3 4]
All Elements after index 5 df[5:] [ 5  6  7  8  9 10]
Some elements in the middle df[3:7] [3 4 5 6]
All even elements df[::2] [ 0  2  4  6  8 10]
All stepped element starting from index 1 df[1::2] [1 3 5 7 9]
----------------------------------------------------------------------------------
👈Reversed Array df[::-1]: [10  9  8  7  6  5  4  3  2  1  0]
👈Stepped Reverse from 7 df[7::-2]: [7 5 3 1]


In [17]:
# Examples using two-dimensional subarrays

print("----------------------------------------------------------------------------------")
print("Second Dataset =", "\n", ds_2)
print("----------------------------------------------------------------------------------")
print("First Five(5) Elements of the two rows ds_2[:5, :5] =", "\n", ds_2[:5, :5])
print("All Elements after index 5 for two rows ds_2[:2, 5:] =", "\n", ds_2[:2, 5:])
print("Some elements in the middle ds_2[:2, 3:7] =", "\n", ds_2[:, 3:7])
print("All stepped elements by 2 ds_2[:, ::2] =", "\n", ds_2[:, ::2])
print("All stepped element starting from index 1 on both rows ds_2[:, 1::2] =", "\n", ds_2[:, 1::2])

# Reversing the array by using negative steps
print("----------------------------------------------------------------------------------")
print("👈Reversed Array for all rows ds_2[:2, ::-1]:", "\n", ds_2[:2, ::-1])
print("👈Stepped Reverse from 7 for all rows ds_2[:, 7::-2]:\n", ds_2[:, 7::-2])

----------------------------------------------------------------------------------
Second Dataset = 
 [[4 4 1 2 4 2 4 3]
 [4 2 4 2 4 1 1 0]]
----------------------------------------------------------------------------------
First Five(5) Elements of the two rows ds_2[:5, :5] = 
 [[4 4 1 2 4]
 [4 2 4 2 4]]
All Elements after index 5 for two rows ds_2[:2, 5:] = 
 [[2 4 3]
 [1 1 0]]
Some elements in the middle ds_2[:2, 3:7] = 
 [[2 4 2 4]
 [2 4 1 1]]
All stepped elements by 2 ds_2[:, ::2] = 
 [[4 1 4 4]
 [4 4 4 1]]
All stepped element starting from index 1 on both rows ds_2[:, 1::2] = 
 [[4 2 2 3]
 [2 2 1 0]]
----------------------------------------------------------------------------------
👈Reversed Array for all rows ds_2[:2, ::-1]: 
 [[3 4 2 4 2 1 4 4]
 [0 1 1 4 2 4 2 4]]
👈Stepped Reverse from 7 for all rows ds_2[:, 7::-2]:
 [[3 2 2 4]
 [0 1 2 2]]


In [18]:
# Clone our ds_2
main_ds = ds_2.copy()

In [19]:
# Subarrays as no-copy views
print("Second Dataset =", "\n", main_ds)

Second Dataset = 
 [[4 4 1 2 4 2 4 3]
 [4 2 4 2 4 1 1 0]]


In [20]:
# Create a 3 by 2 array of our dataset
sub_array = main_ds[:2, :3]
print("Subarray =\n", sub_array)

# Make a change to the subarray
sub_array[0,0] = 10
print("First value of subarray is changed to 10 =\n", sub_array)

# View the original dataset
print("Original dataset is now =\n", main_ds)

Subarray =
 [[4 4 1]
 [4 2 4]]
First value of subarray is changed to 10 =
 [[10  4  1]
 [ 4  2  4]]
Original dataset is now =
 [[10  4  1  2  4  2  4  3]
 [ 4  2  4  2  4  1  1  0]]


In [21]:
# Use .copy() to create a 3 by 2 array of our dataset
sub_array = ds_2[:2, :3].copy()

print("Subarray =\n", sub_array)

# Make a change to the subarray
sub_array[0,0] = 5
print("First value of subarray is changed to 10 =\n", sub_array)

# View the original dataset
print("Original dataset is now =\n", ds_2)

Subarray =
 [[4 4 1]
 [4 2 4]]
First value of subarray is changed to 10 =
 [[5 4 1]
 [4 2 4]]
Original dataset is now =
 [[4 4 1 2 4 2 4 3]
 [4 2 4 2 4 1 1 0]]


### Reshaping Arrays

In [48]:
# Creating a 3 by 4 matrix of numbers from 1-11
new_array = np.arange(1, 13).reshape(3, 4)

# Column vector reshaping
arr_2 = np.arange(1, 4).reshape(3,1)
new_array, arr_2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[1],
        [2],
        [3]]))

#### Array Concatenation

In [55]:
# You can use the np.concatenate, np.vstack and np.hstack for joining two or more arrays together.
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

print("Concatenation: np.concatenate([x, y, z]) = ", np.concatenate([x, y, z]))
print("Vstack: np.vstack([x, y, z]) =\n", np.vstack([x, y, z]))
print("Hstack: np.hstack([x, y, z]) =\n", np.hstack([x, y, z]))

Concatenation: np.concatenate([x, y, z]) =  [1 2 3 4 5 6 7 8 9]
Vstack: np.vstack([x, y, z]) =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Hstack: np.hstack([x, y, z]) =
 [1 2 3 4 5 6 7 8 9]


#### Array Splitting

In [58]:
# You use the np.split, np.hsplit and np.vsplit for spliting arrays into smaller subaarays.
x = np.arange(10)
x_1, x_2, x_3, x_4 = np.split(x, [3, 5, 7])
print(x_1, x_2, x_3, x_4)
# It is important to note that the [3, 5, 7] used above splits the data from those points, that is, @3: x[:3], @5: x[3:5], x[5:7] and @7: x[7:].

[0 1 2] [3 4] [5 6] [7 8 9]


In [65]:
x = np.arange(16).reshape(4, 4)
x_1, x_2 = np.hsplit(x, 2)
print("Horrizontal Split(hsplit):", "\nx_1 =", x_1, "\nx_2 =", x_2)

Horrizontal Split(hsplit): 
x_1 = [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
x_2 = [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [66]:
x_1, x_2 = np.vsplit(x, 2)
print("Vertical Split(vsplit):", "\nx_1 =", x_1, "\nx_2 =", x_2)

Vertical Split(vsplit): 
x_1 = [[0 1 2 3]
 [4 5 6 7]] 
x_2 = [[ 8  9 10 11]
 [12 13 14 15]]
